name: Release

on:
  workflow_dispatch:

jobs:
  merge:
    name: Merge to Master
    runs-on: ubuntu-latest

    steps:
      - name: Check Out master
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0  # Fetch all history for all tags and branches
          token: "${{ secrets.GITHUB_TOKEN }}"

      - run: git merge origin/develop

  bump_version:
    needs: merge
    name: Bump version and create changelog with commitizen
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"      

  trigger_deploy:
    name: Trigger Deploy
    runs-on: ubuntu-latest
    needs: bump_version
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"

      # Still in master, push to force deploy or any action that
      # gets triggered when pushing to master branch.
      - run: git push

      # As now master is one commit ahead of develop, we need to merge back
      # master to develop in order to keep a linear history
      - name: Check Out develop
        uses: actions/checkout@v2
        with:
          ref: develop
          fetch-depth: 0  # Fetch all history for all tags and branches
          token: "${{ secrets.GITHUB_TOKEN }}"

      # Should be fast-forward
      - run: | 
        git merge origin/master
        git push
